### ISSUE TITLE
Shellinabox inside iframe - clicking back in the iframe, parent window scrolls to the top

### ISSUE THREAD

**Issue by KLuka** [shellinabox/shellinabox#191]
_From [pocha.sh...@gmail.com](https://code.google.com/u/108559432150076164220/) on May 24, 2012 14:50:06_

What steps will reproduce the problem? 1. Embed the shellinabox window as iframe (preferrably lower on the page)
2. Click elsewhere 
3. Click back in the shellinabox iframe What is the expected output? What do you see instead? It was expected that the parent window should not have scrolled up. What version of the product are you using? On what operating system? Version 2.10 . OS (where shellinabox installed) - ubuntu. Browser- Firefox 12.0 (tried in various other browsers as well). Please provide any additional information below.

_Original issue: http://code.google.com/p/shellinabox/issues/detail?id=191_

**Comment by KLuka** [comment]
This should be fixed.

**Comment by roryl** [comment]
I can still reproduce this bug on version: "Shell In A Box 2.20 (revision 05b2d36)"
Built from source on CentOS Linux release 7.2.1511 (Core)
Tried in Chrome 53.0.2785.143 m (64-bit) & Firefox 48.0.2

Steps to reproduce: 
1) Using misc/embedded.html, add a large height to the page:

`<body style="min-height:2000px;">`

2) Scroll down, click back in the terminal, it will jump to top of page.

**Comment by GowrishankarGeek** [comment]
- create css file in shell in box
 - Add 
  #vt100 .hidden {
      top: 0px !important
  };
